In [1]:
import numpy as np
import pandas as pd

# Nomor 1

In [2]:
#input

In [3]:
mulai=int(input('mulai:'))
selesai=int(input('selesai:'))

mulai:1
selesai:28


In [4]:
#1 dimensi

In [5]:
np.arange(mulai,selesai)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [6]:
#2 dimensi

In [7]:
np.arange(mulai,selesai).reshape(3,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [8]:
#3 dimensi

In [9]:
np.arange(mulai,selesai).reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# Nomor 2

In [10]:
#input

In [11]:
jumlah=int(input('Banyak Data:'))
mulai=int(input('Mulai:'))
selesai=int(input('Selesai:'))

Banyak Data:16
Mulai:1
Selesai:50


In [12]:
#bangkitkan array 1 dimensi dari random integer

In [13]:
data=np.random.randint(mulai,selesai,jumlah)
data

array([11,  3, 25, 15, 13, 10, 20, 39, 29, 31,  5, 14, 16, 47, 14, 37])

In [14]:
np.random.randint(mulai,selesai,jumlah)

array([ 9, 17, 25, 38, 34, 46,  5, 30, 40, 42, 13, 21, 44, 35, 41,  2])

In [15]:
#dua dimensi

In [16]:
matrix=np.random.randint(mulai,selesai,(4,4))
matrix

array([[17, 15,  7, 45],
       [ 9, 28,  7, 28],
       [33, 27, 45,  6],
       [22, 31, 18, 44]])

In [17]:
#tukar posisi

In [21]:
np.fliplr(matrix)

array([[45,  7, 15, 17],
       [28,  7, 28,  9],
       [ 6, 45, 27, 33],
       [44, 18, 31, 22]])

In [19]:
matrix[:,::-1]

array([[45,  7, 15, 17],
       [28,  7, 28,  9],
       [ 6, 45, 27, 33],
       [44, 18, 31, 22]])

# Nomor 3

In [ ]:
#array 2 dimensi 10x10

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.zeros((10,10)) #belum ada angka 4 nya

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
my_array=np.ones((10,10))*4
my_array[1:-1,1:-1]=0
my_array

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

# Nomor 4

In [ ]:
#buat sebuah series

In [25]:
nomor=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
huruf=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

In [26]:
pd.Series(index=huruf,data=nomor)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

# Nomor 5

In [ ]:
#Series yang terdiri dari angka random integer 1 sampai 5 sebanyak 100

In [32]:
arr=np.random.randint(1,5,100)

In [33]:
a=pd.Series(arr)
a

0     4
1     4
2     3
3     1
4     3
     ..
95    3
96    3
97    3
98    4
99    3
Length: 100, dtype: int32

In [36]:
my_series=pd.Series(np.random.randint(1,5,100))
my_series

0     1
1     4
2     2
3     2
4     3
     ..
95    2
96    1
97    4
98    2
99    1
Length: 100, dtype: int32

In [37]:
my_series.value_counts()

3    28
1    28
4    23
2    21
dtype: int64

In [38]:
pd.DataFrame(my_series.value_counts().reset_index().rename(columns={'index':'value',0:'frekuensi'}).head(2))

value  frekuensi
0      3         28
1      1         28

# Nomor 6

In [39]:
#import seaborn dan load data 'MPG'
import seaborn as sns
mpg=sns.load_dataset('mpg')

In [40]:
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [ ]:
#lakukan describe data selain data numerik

In [41]:
mpg.describe(include=object)

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [ ]:
#tampilkan nama kolom dataframe

In [42]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
#hitung jumlah missing value

In [43]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

# Nomor 7

In [ ]:
#menampilkan data missing value

In [44]:
mpg[mpg['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [45]:
mpg[mpg['horsepower'].isna()].index

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

# Nomor 8

In [46]:
mpg.groupby('model_year').mean()['horsepower']

model_year
70    147.827586
71    107.037037
72    120.178571
73    130.475000
74     94.230769
75    101.066667
76    101.117647
77    105.071429
78     99.694444
79    101.206897
80     77.481481
81     81.035714
82     81.466667
Name: horsepower, dtype: float64

# Nomor 9

In [47]:
def add_horse(x):
    if x['horsepower']<=105:
        return f'lower{x["origin"]}'
    else :
        return f'upper{x["origin"]}'
    


In [53]:
horse_origin=mpg[['horsepower','origin']].apply(add_horse,axis=1)
horse_origin

0         upperusa
1         upperusa
2         upperusa
3         upperusa
4         upperusa
          ...     
393       lowerusa
394    lowereurope
395       lowerusa
396       lowerusa
397       lowerusa
Length: 398, dtype: object

In [54]:
mpg['horse_origin']=horse_origin
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name horse_origin  
0            70     usa  chevrolet chevelle malibu     upperusa  
1            70     usa          buick skylark 320     upperusa  
2            70     usa         plymouth satellite     upperusa  
3            70     usa              amc rebel sst     upperusa  
4            70     usa                ford torino     upperusa  
..          ...     ...                        ...          ...  
393          82     usa            ford mustang gl     lowerusa  
394          82  europe                  vw pickup  lowereurope  
395          82     usa              dodge rampage     lowerusa  
396          82     usa                ford ranger     lowerusa  
397          82     usa                 chevy s-10     lowerusa  

[398 rows x 10 columns]

# Nomor 10

In [ ]:
#buat grouping untuk aggregate yang ditentukan

In [58]:
mpg.groupby('origin')['weight'].agg(['mean','std','sum','count','min','max'])

mean         std     sum  count   min   max
origin                                                    
europe  2423.300000  490.043191  169631     70  1825  3820
japan   2221.227848  320.497248  175477     79  1613  2930
usa     3361.931727  794.792506  837121    249  1800  5140

In [ ]:
#reset index dan penerapan grouping

In [56]:
mpg.groupby('origin')['weight'].agg(['mean','std','sum','count','min','max']).reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140